"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { ArrowLeft, FileCode, FileText, Check, Download, Copy, Loader2 } from "lucide-react"
import type { AnalysisResult } from "@/lib/types"
import { generatePDF } from "@/lib/pdf-generator"

interface ExportScreenProps {
  analysisResult: AnalysisResult
  onBack: () => void
}

export function ExportScreen({ analysisResult, onBack }: ExportScreenProps) {
  const [isExporting, setIsExporting] = useState(false)
  const [isExportingPDF, setIsExportingPDF] = useState(false)
  const [exportComplete, setExportComplete] = useState(false)
  const [exportPDFComplete, setExportPDFComplete] = useState(false)
  const [copied, setCopied] = useState(false)

  const generateMarkdown = () => {
    const totalIssues = analysisResult.issues.length
    const criticalCount = analysisResult.issues.filter((i) => i.severity === "critical").length
    const majorCount = analysisResult.issues.filter((i) => i.severity === "major").length
    const minorCount = analysisResult.issues.filter((i) => i.severity === "minor").length

    return `# UX Audit Report

**Generated by Flow UX AI**  
**Date:** ${new Date().toLocaleDateString()}

---

## Summary

| Metric | Count |
|--------|-------|
| Total Issues | ${totalIssues} |
| Critical | ${criticalCount} |
| Major | ${majorCount} |
| Minor | ${minorCount} |
| Screens Analyzed | ${analysisResult.screenshots.length} |

---

## Issues by Screen

${analysisResult.screenshots
  .map((screenshot) => {
    const issues = analysisResult.issues.filter((i) => i.screenshotId === screenshot.id)
    if (issues.length === 0) return ""

    return `### ${screenshot.name}

${issues
  .map(
    (issue, idx) => `#### ${idx + 1}. [${issue.severity.toUpperCase()}] ${issue.problem}

- **Cause:** ${issue.cause}
- **Fix:** ${issue.fix}
- **Location:** (${issue.coordinates.x}, ${issue.coordinates.y})`,
  )
  .join("\n\n")}`
  })
  .filter(Boolean)
  .join("\n\n---\n\n")}

---

## Severity Guide

- **CRITICAL:** Must fix before launch. Affects usability or accessibility significantly.
- **MAJOR:** Should fix soon. Impacts user experience noticeably.
- **MINOR:** Nice to fix. Small improvements for polish.

---

*Report generated by Flow UX AI*
`
  }

  const handleExport = async () => {
    setIsExporting(true)

    // Generate markdown content
    const markdown = generateMarkdown()

    // Create blob and download
    const blob = new Blob([markdown], { type: "text/markdown" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `ux-audit-report-${new Date().toISOString().split("T")[0]}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)

    setIsExporting(false)
    setExportComplete(true)
    setTimeout(() => setExportComplete(false), 3000)
  }

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generateMarkdown())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleExportPDF = async () => {
    setIsExportingPDF(true)
    try {
      // Small delay to show loading state
      await new Promise((resolve) => setTimeout(resolve, 300))
      generatePDF(analysisResult)
      setExportPDFComplete(true)
      setTimeout(() => setExportPDFComplete(false), 3000)
    } catch (error) {
      console.error("Error generating PDF:", error)
      alert("Failed to generate PDF. Please try again.")
    } finally {
      setIsExportingPDF(false)
    }
  }

  return (
    <div className="min-h-[calc(100vh-3.5rem)] bg-background">
      <div className="mx-auto max-w-4xl p-6">
        {/* Header */}
        <div className="mb-8">
          <Button
            variant="ghost"
            onClick={onBack}
            className="mb-4 -ml-2 gap-2 text-muted-foreground hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Review
          </Button>
          <h1 className="text-2xl font-semibold tracking-tight">Export Report</h1>
          <p className="text-muted-foreground mt-1">Download your UX audit findings in multiple formats</p>
        </div>

        {/* Export Section */}
        <div className="rounded-xl border border-border bg-card p-6 mb-6">
          <div className="flex items-center gap-4 mb-6">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-muted">
              <FileCode className="h-6 w-6 text-foreground" />
            </div>
            <div>
              <h2 className="text-lg font-semibold">Export Report</h2>
              <p className="text-sm text-muted-foreground">
                Download your UX audit findings in multiple formats
              </p>
            </div>
          </div>

          {/* Export Buttons Row */}
          <div className="flex flex-col sm:flex-row gap-3 w-full">
            {/* PDF Export Button - Left (First) */}
            <Button
              variant="secondary"
              onClick={handleExportPDF}
              disabled={isExportingPDF}
              className="gap-2 flex-1 w-full sm:w-auto"
              size="lg"
              aria-label="Download PDF report"
            >
              {isExportingPDF ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Generating PDF...
                </>
              ) : exportPDFComplete ? (
                <>
                  <Check className="h-4 w-4" />
                  Downloaded!
                </>
              ) : (
                <>
                  <FileText className="h-4 w-4" />
                  Download PDF
                </>
              )}
            </Button>

            {/* Markdown Export Buttons - Right */}
            <div className="flex gap-3 flex-1 w-full sm:w-auto">
              <Button
                variant="secondary"
                onClick={handleExport}
                disabled={isExporting}
                className="gap-2 flex-1"
                size="lg"
              >
                {isExporting ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Exporting...
                  </>
                ) : exportComplete ? (
                  <>
                    <Check className="h-4 w-4" />
                    Downloaded!
                  </>
                ) : (
                  <>
                    <Download className="h-4 w-4" />
                    Download .md
                  </>
                )}
              </Button>
              <Button
                variant="secondary"
                onClick={handleCopy}
                className="gap-2"
                size="lg"
              >
                {copied ? (
                  <>
                    <Check className="h-4 w-4" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="h-4 w-4" />
                    Copy
                  </>
                )}
              </Button>
            </div>
          </div>
        </div>

        {/* Preview Panel */}
        <div className="space-y-3">
          <h3 className="text-sm font-medium text-muted-foreground">Preview</h3>
          <div className="rounded-xl border border-border bg-card overflow-hidden">
            <div className="border-b border-border bg-muted/30 px-4 py-2">
              <div className="flex items-center gap-2">
                <div className="h-3 w-3 rounded-full bg-red-500/50" />
                <div className="h-3 w-3 rounded-full bg-yellow-500/50" />
                <div className="h-3 w-3 rounded-full bg-green-500/50" />
                <span className="ml-2 text-xs text-muted-foreground">ux-audit-report.md</span>
              </div>
            </div>
            <pre className="max-h-[500px] overflow-auto p-4 text-xs text-muted-foreground font-mono leading-relaxed whitespace-pre-wrap">
              {generateMarkdown()}
            </pre>
          </div>
        </div>
      </div>
    </div>
  )
}