import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"
import type { AnalysisResult } from "./types"

export function generatePDF(analysisResult: AnalysisResult): void {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  let yPosition = margin

  // Colors for severity levels
  const severityColors = {
    critical: [220, 53, 69], // Red
    major: [255, 193, 7], // Yellow
    minor: [0, 123, 255], // Blue
  }

  // Helper function to add a new page if needed
  const checkPageBreak = (requiredHeight: number) => {
    if (yPosition + requiredHeight > pageHeight - margin) {
      doc.addPage()
      yPosition = margin
      return true
    }
    return false
  }

  // Title
  doc.setFontSize(24)
  doc.setFont("helvetica", "bold")
  doc.text("UX Audit Report", margin, yPosition)
  yPosition += 10

  // Subtitle
  doc.setFontSize(12)
  doc.setFont("helvetica", "normal")
  doc.setTextColor(100, 100, 100)
  doc.text("Generated by Flow UX AI", margin, yPosition)
  yPosition += 5
  doc.text(`Date: ${new Date().toLocaleDateString()}`, margin, yPosition)
  yPosition += 15
  doc.setTextColor(0, 0, 0)

  // Summary Section
  doc.setFontSize(16)
  doc.setFont("helvetica", "bold")
  doc.text("Summary", margin, yPosition)
  yPosition += 10

  const totalIssues = analysisResult.issues.length
  const criticalCount = analysisResult.issues.filter((i) => i.severity === "critical").length
  const majorCount = analysisResult.issues.filter((i) => i.severity === "major").length
  const minorCount = analysisResult.issues.filter((i) => i.severity === "minor").length

  // Summary Table
  autoTable(doc, {
    startY: yPosition,
    head: [["Metric", "Count"]],
    body: [
      ["Total Issues", totalIssues.toString()],
      ["Critical Issues", criticalCount.toString()],
      ["Major Issues", majorCount.toString()],
      ["Minor Issues", minorCount.toString()],
      ["Screens Analyzed", analysisResult.screenshots.length.toString()],
    ],
    theme: "striped",
    headStyles: { fillColor: [66, 139, 202], textColor: 255, fontStyle: "bold" },
    margin: { left: margin, right: margin },
  })

  yPosition = (doc as any).lastAutoTable.finalY + 15

  // Issues by Screen
  doc.setFontSize(16)
  doc.setFont("helvetica", "bold")
  doc.text("Issues by Screen", margin, yPosition)
  yPosition += 10

  analysisResult.screenshots.forEach((screenshot) => {
    const issues = analysisResult.issues.filter((i) => i.screenshotId === screenshot.id)
    if (issues.length === 0) return

    checkPageBreak(30)

    // Screenshot name
    doc.setFontSize(14)
    doc.setFont("helvetica", "bold")
    doc.text(screenshot.name, margin, yPosition)
    yPosition += 8

    // Issues table for this screenshot
    const tableData = issues.map((issue, idx) => {
      const severityColor = severityColors[issue.severity]
      return [
        (idx + 1).toString(),
        issue.severity.toUpperCase(),
        issue.problem,
        `(${issue.coordinates.x}, ${issue.coordinates.y})`,
      ]
    })

    autoTable(doc, {
      startY: yPosition,
      head: [["#", "Severity", "Problem", "Location"]],
      body: tableData,
      theme: "striped",
      headStyles: { fillColor: [66, 139, 202], textColor: 255, fontStyle: "bold" },
      columnStyles: {
        1: {
          cellWidth: 30,
        },
        2: {
          cellWidth: 80,
        },
        3: {
          cellWidth: 50,
        },
      },
      didParseCell: (data) => {
        if (data.row.index >= 0 && data.column.index === 1) {
          // Color severity column
          const issue = issues[data.row.index]
          const color = severityColors[issue.severity]
          data.cell.styles.fillColor = color as [number, number, number]
          data.cell.styles.textColor = 255
          data.cell.styles.fontStyle = "bold"
        }
      },
      margin: { left: margin, right: margin },
    })

    yPosition = (doc as any).lastAutoTable.finalY + 10

    // Add detailed information for each issue
    issues.forEach((issue) => {
      checkPageBreak(25)

      doc.setFontSize(10)
      doc.setFont("helvetica", "bold")
      const severityColor = severityColors[issue.severity]
      doc.setTextColor(severityColor[0], severityColor[1], severityColor[2])
      doc.text(`${issue.severity.toUpperCase()}: ${issue.problem}`, margin + 5, yPosition)
      doc.setTextColor(0, 0, 0)
      yPosition += 6

      doc.setFontSize(9)
      doc.setFont("helvetica", "normal")
      doc.text(`Cause: ${issue.cause}`, margin + 5, yPosition)
      yPosition += 5
      doc.text(`Fix: ${issue.fix}`, margin + 5, yPosition)
      yPosition += 8
    })

    yPosition += 5
  })

  // Severity Guide
  checkPageBreak(40)
  doc.setFontSize(16)
  doc.setFont("helvetica", "bold")
  doc.text("Severity Guide", margin, yPosition)
  yPosition += 10

  doc.setFontSize(10)
  doc.setFont("helvetica", "normal")
  const guideItems = [
    {
      severity: "CRITICAL",
      description: "Must fix before launch. Affects usability or accessibility significantly.",
      color: severityColors.critical,
    },
    {
      severity: "MAJOR",
      description: "Should fix soon. Impacts user experience noticeably.",
      color: severityColors.major,
    },
    {
      severity: "MINOR",
      description: "Nice to fix. Small improvements for polish.",
      color: severityColors.minor,
    },
  ]

  guideItems.forEach((item) => {
    checkPageBreak(15)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(item.color[0], item.color[1], item.color[2])
    doc.text(`• ${item.severity}:`, margin + 5, yPosition)
    doc.setTextColor(0, 0, 0)
    doc.setFont("helvetica", "normal")
    const textWidth = pageWidth - margin * 2 - 10
    const splitText = doc.splitTextToSize(item.description, textWidth - 30)
    doc.text(splitText, margin + 25, yPosition)
    yPosition += splitText.length * 5 + 3
  })

  // Footer
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(
      `Page ${i} of ${totalPages} | Report generated by Flow UX AI`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" },
    )
  }

  // Download the PDF
  const fileName = `ux-audit-report-${new Date().toISOString().split("T")[0]}.pdf`
  doc.save(fileName)
}

